### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by danomatic** [longlho/ts-transform-css-modules#1]
Can you give an example of how this is used?  Is it via `tsconfig.json`, `webpack.config.js` or something else?

**Comment by longlho** [comment]
Hi there,

Right now you'd have to write a wrapper around the TS compiler API. Check
out compile.ts for an example.

**Comment by longlho** [comment]
@danomatic the unit test should give you some idea as well. Right now TS doesn't allow custom transformation via `tsconfig.json`. I do have a [PR](https://github.com/TypeStrong/ts-loader/pull/535) in `ts-loader` so that it can be used in webpack, but not traction so far

**Comment by goloveychuk** [comment]
@longlho I already submitted pr to awesome-typescript-loader - it's already merged.
But it don't support when compiler is forked. (with checkerplugin)

**Comment by goloveychuk** [comment]
also - as I know, better to do your job - write ts plugin, to support other files than ts or js. 
look at https://github.com/Quramy/typed-css-modules/issues/29

**Comment by longlho** [comment]
I'm closing this issue since plugin won't solve your problem anw. See https://github.com/Microsoft/TypeScript/issues/16607
