### ISSUE TITLE
Ttypescript usage?

### ISSUE THREAD

**Issue by DanielRamosAcosta** [longlho/ts-transform-css-modules#16]
I'm trying to use this plugin using [ttypescript](https://github.com/cevek/ttypescript) (as you are mentioned as a reference plugin), I'm getting this error:

```
Module build failed: Error: tsconfig.json > plugins: "ts-transform-css-modules" is not a plugin module: {}
```

I can't find any specific docs on this...

**Comment by longlho** [comment]
looks like it doesn't work bc I don't expose `default` as the transformer itself which I don't plan to since I plan to `export` more things. 
Maybe @cevek should consider supporting `package-name/some-file` instead of just package name for more flexibility?

**Comment by cevek** [comment]
It was my mistake, I put incorrect examples in readme.
So for this transformer config should look like: 
`{transform: "ts-transform-css-modules/dist/transform", type: "config", ...somePluginConfig}`

Also you need to update ttypescript to `1.4.0` cause previous version provides full object as config, but some transformers check of excess properties

**Comment by longlho** [comment]
cool I'll close out this issue then
