### ISSUE TITLE
Usage in ts-loader?

### ISSUE THREAD

**Issue by planetrenner-martin** [longlho/ts-transform-css-modules#4]
Is it possible to use this transformer together with ts-loader, in order to transform CSS files automatically during the build?

Setup is webpack 3.3.0, ts-loader 2.3.1 and typescript 2.4.2.

According to the documentation of ts-loader, it should be possible to include custom transformers (`getCustomTransformers()`). I tried

```javascript
const transformCss = require('ts-transform-css-modules');

module: {
    rules: {
        {test: /\.tsx?$/, use: [{loader: 'ts-loader', options: {getCustomTransformers: () => ({before: [transformCss()]})}}, 'tslint-loader']},
```

but I get an error message: `TypeError: transformCss is not a function`.

**Comment by longlho** [comment]
this uses `import` so u need `require('...').default`

**Comment by planetrenner-martin** [comment]
Hi.

`require('...').default` resulted in the same error, but `require('...').transform` seems to work. 

I added the parameter to `transformCss()`:

```javascript
{before: [transformCss({generateScopedName: '[name]__[local]___[hash:base64:5]'})]}
```

With that, the build runs without any errors related to ts-transform.

But now I am stuck at the famous
```
ERROR in ./source/components/App.tsx
(3,25): error TS2307: Cannot find module './app.css'.
```

The code of App.tsx looks like this:

```javascript
import * as styles from './app.css';

export default class App extends React.Component<{}, {}> {
...
}
```

I will have a look on that tonight. I thought, that adding the transformer to the 'tsx' rule will resolve all my problems mit Typescript and css modules :-)

**Comment by longlho** [comment]
TBH I have not tested it w/ webpack since wp has a separate CSS Modules system. The primary difference also is how WP "resolves" thing, which is probably the reason why ur getting file locating issue.

**Comment by Schlesiger** [comment]
@planetrenner-martin I think I've just been down the same rabbit hole. `ts-transform-css-modules` doesn't resolve `.css` imports as far as I know. I think that is why even in their tests, they require a [global.d.ts](https://github.com/longlho/ts-transform-css-modules/blob/master/test/fixture/global.d.ts) to predefine `*.css`. That is likely what you are missing.

Does the transformer only append the hash to css class names? Isn't this also possible if you are using webpack, `ts-loader` or `awesome-typescript-loader`, and `css-loader` with cssModules configured? Does it make [global.d.ts](https://github.com/longlho/ts-transform-css-modules/blob/master/test/fixture/global.d.ts) obsolete, or does it generate the `.css.d.ts`?

I am also having difficulty getting it to work. After adding the [global.d.ts](https://github.com/longlho/ts-transform-css-modules/blob/master/test/fixture/global.d.ts) to my project, I get the error `Cannot read property 'kind' of undefined`. If I try `typescript@next`, I get a different error `Cannot set property text of [object Object] which has only a getter` on `transform.js:65:31`.

**Comment by longlho** [comment]
the `global.d.ts` is only for testing purpose, in a production project you'd generate `.css.d.ts` by using this plugin and output the classnames out, or using 1 of the open source projects specifically to extract `.css.d.ts`

**Comment by Schlesiger** [comment]
Oh excellent; that is what I was hoping. It also looks like my issue with `typescript@^2.4.0` may be related to issue [#17348](https://github.com/Microsoft/TypeScript/issues/17384). I tried the exact version in this projects `package.json` and also tried using the exact same `tsconfig.json` to no avail. I look forward to giving this a try once resolved.

**Comment by planetrenner-martin** [comment]
@Schlesiger I went back to `typings-for-css-modules-loader`. But with the (well known) problem that you have to compile at least twice. I thought that `ts-transform-css-modules` would close this gap, but it looks like the primary focus of this project is not fitting 100% with the "webpack css ts" problem. But it would be awesome if it would :-)

**Comment by Schlesiger** [comment]
@longho I managed to get everything working, however, if I remove the [global.d.ts](https://github.com/longlho/ts-transform-css-modules/blob/master/test/fixture/global.d.ts) the build still fails with `Cannot find module './index.css'`. If I leave `global.d.ts`, it builds, but no `.d.ts` file is generated. Is a `.d.ts` supposed to be generated?

Lastly, this transformer interferes with [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules). I receive the build error `Cannot use styleName attribute without importing at least one stylesheet`.

It would be great if there was an option to leave the `.css` import alone and instead only generate the `.d.ts`. This way it would pipe seamlessly into Babel and its variety of plugins. Otherwise, great work! 

@planetrenner-martin, you outline the [typings-for-css-modules-loader](https://github.com/Jimdo/typings-for-css-modules-loader) issue exactly. The double build is a real pain - so much that in my case it just isn't worth it for `.css` intellisense.

**Comment by longlho** [comment]
I can throw in some docs/guidelines on generating `.d.ts`. It'll just be a separate example script thou

**Comment by longlho** [comment]
@Schlesiger This is an example of extracting type def in CSS to `d.ts` file: https://gist.github.com/longlho/3c974b7c772d1db801b31624204381f7

**Comment by Schlesiger** [comment]
Thanks! I'll be away for a couple weeks but I'll give it a try shortly after I get back.

**Comment by longlho** [comment]
closing this since it's a non-issue but feel free to continue the discussion
